package com.pusilkom.base.model;

import java.io.Serializable;

public class DokumenKerjasama implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dokumen_kerjasama.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dokumen_kerjasama.id_kerjasama
     *
     * @mbg.generated
     */
    private Integer idKerjasama;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dokumen_kerjasama.id_tipe_dokumen
     *
     * @mbg.generated
     */
    private Integer idTipeDokumen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dokumen_kerjasama.nama_dokumen
     *
     * @mbg.generated
     */
    private String namaDokumen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dokumen_kerjasama.nama_file
     *
     * @mbg.generated
     */
    private String namaFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dokumen_kerjasama.tahun_dokumen
     *
     * @mbg.generated
     */
    private String tahunDokumen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dokumen_kerjasama.file_path
     *
     * @mbg.generated
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dokumen_kerjasama
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dokumen_kerjasama.id
     *
     * @return the value of dokumen_kerjasama.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dokumen_kerjasama.id
     *
     * @param id the value for dokumen_kerjasama.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dokumen_kerjasama.id_kerjasama
     *
     * @return the value of dokumen_kerjasama.id_kerjasama
     *
     * @mbg.generated
     */
    public Integer getIdKerjasama() {
        return idKerjasama;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dokumen_kerjasama.id_kerjasama
     *
     * @param idKerjasama the value for dokumen_kerjasama.id_kerjasama
     *
     * @mbg.generated
     */
    public void setIdKerjasama(Integer idKerjasama) {
        this.idKerjasama = idKerjasama;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dokumen_kerjasama.id_tipe_dokumen
     *
     * @return the value of dokumen_kerjasama.id_tipe_dokumen
     *
     * @mbg.generated
     */
    public Integer getIdTipeDokumen() {
        return idTipeDokumen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dokumen_kerjasama.id_tipe_dokumen
     *
     * @param idTipeDokumen the value for dokumen_kerjasama.id_tipe_dokumen
     *
     * @mbg.generated
     */
    public void setIdTipeDokumen(Integer idTipeDokumen) {
        this.idTipeDokumen = idTipeDokumen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dokumen_kerjasama.nama_dokumen
     *
     * @return the value of dokumen_kerjasama.nama_dokumen
     *
     * @mbg.generated
     */
    public String getNamaDokumen() {
        return namaDokumen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dokumen_kerjasama.nama_dokumen
     *
     * @param namaDokumen the value for dokumen_kerjasama.nama_dokumen
     *
     * @mbg.generated
     */
    public void setNamaDokumen(String namaDokumen) {
        this.namaDokumen = namaDokumen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dokumen_kerjasama.nama_file
     *
     * @return the value of dokumen_kerjasama.nama_file
     *
     * @mbg.generated
     */
    public String getNamaFile() {
        return namaFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dokumen_kerjasama.nama_file
     *
     * @param namaFile the value for dokumen_kerjasama.nama_file
     *
     * @mbg.generated
     */
    public void setNamaFile(String namaFile) {
        this.namaFile = namaFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dokumen_kerjasama.tahun_dokumen
     *
     * @return the value of dokumen_kerjasama.tahun_dokumen
     *
     * @mbg.generated
     */
    public String getTahunDokumen() {
        return tahunDokumen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dokumen_kerjasama.tahun_dokumen
     *
     * @param tahunDokumen the value for dokumen_kerjasama.tahun_dokumen
     *
     * @mbg.generated
     */
    public void setTahunDokumen(String tahunDokumen) {
        this.tahunDokumen = tahunDokumen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dokumen_kerjasama.file_path
     *
     * @return the value of dokumen_kerjasama.file_path
     *
     * @mbg.generated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dokumen_kerjasama.file_path
     *
     * @param filePath the value for dokumen_kerjasama.file_path
     *
     * @mbg.generated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dokumen_kerjasama
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DokumenKerjasama other = (DokumenKerjasama) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIdKerjasama() == null ? other.getIdKerjasama() == null : this.getIdKerjasama().equals(other.getIdKerjasama()))
            && (this.getIdTipeDokumen() == null ? other.getIdTipeDokumen() == null : this.getIdTipeDokumen().equals(other.getIdTipeDokumen()))
            && (this.getNamaDokumen() == null ? other.getNamaDokumen() == null : this.getNamaDokumen().equals(other.getNamaDokumen()))
            && (this.getNamaFile() == null ? other.getNamaFile() == null : this.getNamaFile().equals(other.getNamaFile()))
            && (this.getTahunDokumen() == null ? other.getTahunDokumen() == null : this.getTahunDokumen().equals(other.getTahunDokumen()))
            && (this.getFilePath() == null ? other.getFilePath() == null : this.getFilePath().equals(other.getFilePath()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dokumen_kerjasama
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIdKerjasama() == null) ? 0 : getIdKerjasama().hashCode());
        result = prime * result + ((getIdTipeDokumen() == null) ? 0 : getIdTipeDokumen().hashCode());
        result = prime * result + ((getNamaDokumen() == null) ? 0 : getNamaDokumen().hashCode());
        result = prime * result + ((getNamaFile() == null) ? 0 : getNamaFile().hashCode());
        result = prime * result + ((getTahunDokumen() == null) ? 0 : getTahunDokumen().hashCode());
        result = prime * result + ((getFilePath() == null) ? 0 : getFilePath().hashCode());
        return result;
    }
}