package com.pusilkom.base.model;

import java.util.ArrayList;
import java.util.List;

public class InstitusiExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table institusi
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table institusi
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table institusi
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institusi
     *
     * @mbg.generated
     */
    public InstitusiExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institusi
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institusi
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institusi
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institusi
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institusi
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institusi
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institusi
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institusi
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institusi
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institusi
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table institusi
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdParentInstitusiIsNull() {
            addCriterion("id_parent_institusi is null");
            return (Criteria) this;
        }

        public Criteria andIdParentInstitusiIsNotNull() {
            addCriterion("id_parent_institusi is not null");
            return (Criteria) this;
        }

        public Criteria andIdParentInstitusiEqualTo(Integer value) {
            addCriterion("id_parent_institusi =", value, "idParentInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdParentInstitusiNotEqualTo(Integer value) {
            addCriterion("id_parent_institusi <>", value, "idParentInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdParentInstitusiGreaterThan(Integer value) {
            addCriterion("id_parent_institusi >", value, "idParentInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdParentInstitusiGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_parent_institusi >=", value, "idParentInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdParentInstitusiLessThan(Integer value) {
            addCriterion("id_parent_institusi <", value, "idParentInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdParentInstitusiLessThanOrEqualTo(Integer value) {
            addCriterion("id_parent_institusi <=", value, "idParentInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdParentInstitusiIn(List<Integer> values) {
            addCriterion("id_parent_institusi in", values, "idParentInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdParentInstitusiNotIn(List<Integer> values) {
            addCriterion("id_parent_institusi not in", values, "idParentInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdParentInstitusiBetween(Integer value1, Integer value2) {
            addCriterion("id_parent_institusi between", value1, value2, "idParentInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdParentInstitusiNotBetween(Integer value1, Integer value2) {
            addCriterion("id_parent_institusi not between", value1, value2, "idParentInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdNegaraIsNull() {
            addCriterion("id_negara is null");
            return (Criteria) this;
        }

        public Criteria andIdNegaraIsNotNull() {
            addCriterion("id_negara is not null");
            return (Criteria) this;
        }

        public Criteria andIdNegaraEqualTo(Integer value) {
            addCriterion("id_negara =", value, "idNegara");
            return (Criteria) this;
        }

        public Criteria andIdNegaraNotEqualTo(Integer value) {
            addCriterion("id_negara <>", value, "idNegara");
            return (Criteria) this;
        }

        public Criteria andIdNegaraGreaterThan(Integer value) {
            addCriterion("id_negara >", value, "idNegara");
            return (Criteria) this;
        }

        public Criteria andIdNegaraGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_negara >=", value, "idNegara");
            return (Criteria) this;
        }

        public Criteria andIdNegaraLessThan(Integer value) {
            addCriterion("id_negara <", value, "idNegara");
            return (Criteria) this;
        }

        public Criteria andIdNegaraLessThanOrEqualTo(Integer value) {
            addCriterion("id_negara <=", value, "idNegara");
            return (Criteria) this;
        }

        public Criteria andIdNegaraIn(List<Integer> values) {
            addCriterion("id_negara in", values, "idNegara");
            return (Criteria) this;
        }

        public Criteria andIdNegaraNotIn(List<Integer> values) {
            addCriterion("id_negara not in", values, "idNegara");
            return (Criteria) this;
        }

        public Criteria andIdNegaraBetween(Integer value1, Integer value2) {
            addCriterion("id_negara between", value1, value2, "idNegara");
            return (Criteria) this;
        }

        public Criteria andIdNegaraNotBetween(Integer value1, Integer value2) {
            addCriterion("id_negara not between", value1, value2, "idNegara");
            return (Criteria) this;
        }

        public Criteria andIdTipeInstitusiIsNull() {
            addCriterion("id_tipe_institusi is null");
            return (Criteria) this;
        }

        public Criteria andIdTipeInstitusiIsNotNull() {
            addCriterion("id_tipe_institusi is not null");
            return (Criteria) this;
        }

        public Criteria andIdTipeInstitusiEqualTo(Integer value) {
            addCriterion("id_tipe_institusi =", value, "idTipeInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdTipeInstitusiNotEqualTo(Integer value) {
            addCriterion("id_tipe_institusi <>", value, "idTipeInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdTipeInstitusiGreaterThan(Integer value) {
            addCriterion("id_tipe_institusi >", value, "idTipeInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdTipeInstitusiGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_tipe_institusi >=", value, "idTipeInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdTipeInstitusiLessThan(Integer value) {
            addCriterion("id_tipe_institusi <", value, "idTipeInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdTipeInstitusiLessThanOrEqualTo(Integer value) {
            addCriterion("id_tipe_institusi <=", value, "idTipeInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdTipeInstitusiIn(List<Integer> values) {
            addCriterion("id_tipe_institusi in", values, "idTipeInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdTipeInstitusiNotIn(List<Integer> values) {
            addCriterion("id_tipe_institusi not in", values, "idTipeInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdTipeInstitusiBetween(Integer value1, Integer value2) {
            addCriterion("id_tipe_institusi between", value1, value2, "idTipeInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdTipeInstitusiNotBetween(Integer value1, Integer value2) {
            addCriterion("id_tipe_institusi not between", value1, value2, "idTipeInstitusi");
            return (Criteria) this;
        }

        public Criteria andKodeSsoIsNull() {
            addCriterion("kode_sso is null");
            return (Criteria) this;
        }

        public Criteria andKodeSsoIsNotNull() {
            addCriterion("kode_sso is not null");
            return (Criteria) this;
        }

        public Criteria andKodeSsoEqualTo(String value) {
            addCriterion("kode_sso =", value, "kodeSso");
            return (Criteria) this;
        }

        public Criteria andKodeSsoNotEqualTo(String value) {
            addCriterion("kode_sso <>", value, "kodeSso");
            return (Criteria) this;
        }

        public Criteria andKodeSsoGreaterThan(String value) {
            addCriterion("kode_sso >", value, "kodeSso");
            return (Criteria) this;
        }

        public Criteria andKodeSsoGreaterThanOrEqualTo(String value) {
            addCriterion("kode_sso >=", value, "kodeSso");
            return (Criteria) this;
        }

        public Criteria andKodeSsoLessThan(String value) {
            addCriterion("kode_sso <", value, "kodeSso");
            return (Criteria) this;
        }

        public Criteria andKodeSsoLessThanOrEqualTo(String value) {
            addCriterion("kode_sso <=", value, "kodeSso");
            return (Criteria) this;
        }

        public Criteria andKodeSsoLike(String value) {
            addCriterion("kode_sso like", value, "kodeSso");
            return (Criteria) this;
        }

        public Criteria andKodeSsoNotLike(String value) {
            addCriterion("kode_sso not like", value, "kodeSso");
            return (Criteria) this;
        }

        public Criteria andKodeSsoIn(List<String> values) {
            addCriterion("kode_sso in", values, "kodeSso");
            return (Criteria) this;
        }

        public Criteria andKodeSsoNotIn(List<String> values) {
            addCriterion("kode_sso not in", values, "kodeSso");
            return (Criteria) this;
        }

        public Criteria andKodeSsoBetween(String value1, String value2) {
            addCriterion("kode_sso between", value1, value2, "kodeSso");
            return (Criteria) this;
        }

        public Criteria andKodeSsoNotBetween(String value1, String value2) {
            addCriterion("kode_sso not between", value1, value2, "kodeSso");
            return (Criteria) this;
        }

        public Criteria andNamaIsNull() {
            addCriterion("nama is null");
            return (Criteria) this;
        }

        public Criteria andNamaIsNotNull() {
            addCriterion("nama is not null");
            return (Criteria) this;
        }

        public Criteria andNamaEqualTo(String value) {
            addCriterion("nama =", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaNotEqualTo(String value) {
            addCriterion("nama <>", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaGreaterThan(String value) {
            addCriterion("nama >", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaGreaterThanOrEqualTo(String value) {
            addCriterion("nama >=", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaLessThan(String value) {
            addCriterion("nama <", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaLessThanOrEqualTo(String value) {
            addCriterion("nama <=", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaLike(String value) {
            addCriterion("nama like", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaNotLike(String value) {
            addCriterion("nama not like", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaIn(List<String> values) {
            addCriterion("nama in", values, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaNotIn(List<String> values) {
            addCriterion("nama not in", values, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaBetween(String value1, String value2) {
            addCriterion("nama between", value1, value2, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaNotBetween(String value1, String value2) {
            addCriterion("nama not between", value1, value2, "nama");
            return (Criteria) this;
        }

        public Criteria andAlamatIsNull() {
            addCriterion("alamat is null");
            return (Criteria) this;
        }

        public Criteria andAlamatIsNotNull() {
            addCriterion("alamat is not null");
            return (Criteria) this;
        }

        public Criteria andAlamatEqualTo(String value) {
            addCriterion("alamat =", value, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatNotEqualTo(String value) {
            addCriterion("alamat <>", value, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatGreaterThan(String value) {
            addCriterion("alamat >", value, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatGreaterThanOrEqualTo(String value) {
            addCriterion("alamat >=", value, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatLessThan(String value) {
            addCriterion("alamat <", value, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatLessThanOrEqualTo(String value) {
            addCriterion("alamat <=", value, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatLike(String value) {
            addCriterion("alamat like", value, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatNotLike(String value) {
            addCriterion("alamat not like", value, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatIn(List<String> values) {
            addCriterion("alamat in", values, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatNotIn(List<String> values) {
            addCriterion("alamat not in", values, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatBetween(String value1, String value2) {
            addCriterion("alamat between", value1, value2, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatNotBetween(String value1, String value2) {
            addCriterion("alamat not between", value1, value2, "alamat");
            return (Criteria) this;
        }

        public Criteria andIsUnhanIsNull() {
            addCriterion("is_unhan is null");
            return (Criteria) this;
        }

        public Criteria andIsUnhanIsNotNull() {
            addCriterion("is_unhan is not null");
            return (Criteria) this;
        }

        public Criteria andIsUnhanEqualTo(Boolean value) {
            addCriterion("is_unhan =", value, "isUnhan");
            return (Criteria) this;
        }

        public Criteria andIsUnhanNotEqualTo(Boolean value) {
            addCriterion("is_unhan <>", value, "isUnhan");
            return (Criteria) this;
        }

        public Criteria andIsUnhanGreaterThan(Boolean value) {
            addCriterion("is_unhan >", value, "isUnhan");
            return (Criteria) this;
        }

        public Criteria andIsUnhanGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_unhan >=", value, "isUnhan");
            return (Criteria) this;
        }

        public Criteria andIsUnhanLessThan(Boolean value) {
            addCriterion("is_unhan <", value, "isUnhan");
            return (Criteria) this;
        }

        public Criteria andIsUnhanLessThanOrEqualTo(Boolean value) {
            addCriterion("is_unhan <=", value, "isUnhan");
            return (Criteria) this;
        }

        public Criteria andIsUnhanIn(List<Boolean> values) {
            addCriterion("is_unhan in", values, "isUnhan");
            return (Criteria) this;
        }

        public Criteria andIsUnhanNotIn(List<Boolean> values) {
            addCriterion("is_unhan not in", values, "isUnhan");
            return (Criteria) this;
        }

        public Criteria andIsUnhanBetween(Boolean value1, Boolean value2) {
            addCriterion("is_unhan between", value1, value2, "isUnhan");
            return (Criteria) this;
        }

        public Criteria andIsUnhanNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_unhan not between", value1, value2, "isUnhan");
            return (Criteria) this;
        }

        public Criteria andKodeSsoLikeInsensitive(String value) {
            addCriterion("upper(kode_sso) like", value.toUpperCase(), "kodeSso");
            return (Criteria) this;
        }

        public Criteria andNamaLikeInsensitive(String value) {
            addCriterion("upper(nama) like", value.toUpperCase(), "nama");
            return (Criteria) this;
        }

        public Criteria andAlamatLikeInsensitive(String value) {
            addCriterion("upper(alamat) like", value.toUpperCase(), "alamat");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table institusi
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table institusi
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}