package com.pusilkom.base.model;

import java.util.ArrayList;
import java.util.List;

public class PenanggungJawabExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table penanggung_jawab
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table penanggung_jawab
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table penanggung_jawab
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penanggung_jawab
     *
     * @mbg.generated
     */
    public PenanggungJawabExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penanggung_jawab
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penanggung_jawab
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penanggung_jawab
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penanggung_jawab
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penanggung_jawab
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penanggung_jawab
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penanggung_jawab
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penanggung_jawab
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penanggung_jawab
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penanggung_jawab
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table penanggung_jawab
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdKerjasamaIsNull() {
            addCriterion("id_kerjasama is null");
            return (Criteria) this;
        }

        public Criteria andIdKerjasamaIsNotNull() {
            addCriterion("id_kerjasama is not null");
            return (Criteria) this;
        }

        public Criteria andIdKerjasamaEqualTo(Integer value) {
            addCriterion("id_kerjasama =", value, "idKerjasama");
            return (Criteria) this;
        }

        public Criteria andIdKerjasamaNotEqualTo(Integer value) {
            addCriterion("id_kerjasama <>", value, "idKerjasama");
            return (Criteria) this;
        }

        public Criteria andIdKerjasamaGreaterThan(Integer value) {
            addCriterion("id_kerjasama >", value, "idKerjasama");
            return (Criteria) this;
        }

        public Criteria andIdKerjasamaGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_kerjasama >=", value, "idKerjasama");
            return (Criteria) this;
        }

        public Criteria andIdKerjasamaLessThan(Integer value) {
            addCriterion("id_kerjasama <", value, "idKerjasama");
            return (Criteria) this;
        }

        public Criteria andIdKerjasamaLessThanOrEqualTo(Integer value) {
            addCriterion("id_kerjasama <=", value, "idKerjasama");
            return (Criteria) this;
        }

        public Criteria andIdKerjasamaIn(List<Integer> values) {
            addCriterion("id_kerjasama in", values, "idKerjasama");
            return (Criteria) this;
        }

        public Criteria andIdKerjasamaNotIn(List<Integer> values) {
            addCriterion("id_kerjasama not in", values, "idKerjasama");
            return (Criteria) this;
        }

        public Criteria andIdKerjasamaBetween(Integer value1, Integer value2) {
            addCriterion("id_kerjasama between", value1, value2, "idKerjasama");
            return (Criteria) this;
        }

        public Criteria andIdKerjasamaNotBetween(Integer value1, Integer value2) {
            addCriterion("id_kerjasama not between", value1, value2, "idKerjasama");
            return (Criteria) this;
        }

        public Criteria andIdInstitusiIsNull() {
            addCriterion("id_institusi is null");
            return (Criteria) this;
        }

        public Criteria andIdInstitusiIsNotNull() {
            addCriterion("id_institusi is not null");
            return (Criteria) this;
        }

        public Criteria andIdInstitusiEqualTo(Integer value) {
            addCriterion("id_institusi =", value, "idInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdInstitusiNotEqualTo(Integer value) {
            addCriterion("id_institusi <>", value, "idInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdInstitusiGreaterThan(Integer value) {
            addCriterion("id_institusi >", value, "idInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdInstitusiGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_institusi >=", value, "idInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdInstitusiLessThan(Integer value) {
            addCriterion("id_institusi <", value, "idInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdInstitusiLessThanOrEqualTo(Integer value) {
            addCriterion("id_institusi <=", value, "idInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdInstitusiIn(List<Integer> values) {
            addCriterion("id_institusi in", values, "idInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdInstitusiNotIn(List<Integer> values) {
            addCriterion("id_institusi not in", values, "idInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdInstitusiBetween(Integer value1, Integer value2) {
            addCriterion("id_institusi between", value1, value2, "idInstitusi");
            return (Criteria) this;
        }

        public Criteria andIdInstitusiNotBetween(Integer value1, Integer value2) {
            addCriterion("id_institusi not between", value1, value2, "idInstitusi");
            return (Criteria) this;
        }

        public Criteria andNamaIsNull() {
            addCriterion("nama is null");
            return (Criteria) this;
        }

        public Criteria andNamaIsNotNull() {
            addCriterion("nama is not null");
            return (Criteria) this;
        }

        public Criteria andNamaEqualTo(String value) {
            addCriterion("nama =", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaNotEqualTo(String value) {
            addCriterion("nama <>", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaGreaterThan(String value) {
            addCriterion("nama >", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaGreaterThanOrEqualTo(String value) {
            addCriterion("nama >=", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaLessThan(String value) {
            addCriterion("nama <", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaLessThanOrEqualTo(String value) {
            addCriterion("nama <=", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaLike(String value) {
            addCriterion("nama like", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaNotLike(String value) {
            addCriterion("nama not like", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaIn(List<String> values) {
            addCriterion("nama in", values, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaNotIn(List<String> values) {
            addCriterion("nama not in", values, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaBetween(String value1, String value2) {
            addCriterion("nama between", value1, value2, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaNotBetween(String value1, String value2) {
            addCriterion("nama not between", value1, value2, "nama");
            return (Criteria) this;
        }

        public Criteria andAlamatIsNull() {
            addCriterion("alamat is null");
            return (Criteria) this;
        }

        public Criteria andAlamatIsNotNull() {
            addCriterion("alamat is not null");
            return (Criteria) this;
        }

        public Criteria andAlamatEqualTo(String value) {
            addCriterion("alamat =", value, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatNotEqualTo(String value) {
            addCriterion("alamat <>", value, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatGreaterThan(String value) {
            addCriterion("alamat >", value, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatGreaterThanOrEqualTo(String value) {
            addCriterion("alamat >=", value, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatLessThan(String value) {
            addCriterion("alamat <", value, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatLessThanOrEqualTo(String value) {
            addCriterion("alamat <=", value, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatLike(String value) {
            addCriterion("alamat like", value, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatNotLike(String value) {
            addCriterion("alamat not like", value, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatIn(List<String> values) {
            addCriterion("alamat in", values, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatNotIn(List<String> values) {
            addCriterion("alamat not in", values, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatBetween(String value1, String value2) {
            addCriterion("alamat between", value1, value2, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatNotBetween(String value1, String value2) {
            addCriterion("alamat not between", value1, value2, "alamat");
            return (Criteria) this;
        }

        public Criteria andJabatanIsNull() {
            addCriterion("jabatan is null");
            return (Criteria) this;
        }

        public Criteria andJabatanIsNotNull() {
            addCriterion("jabatan is not null");
            return (Criteria) this;
        }

        public Criteria andJabatanEqualTo(String value) {
            addCriterion("jabatan =", value, "jabatan");
            return (Criteria) this;
        }

        public Criteria andJabatanNotEqualTo(String value) {
            addCriterion("jabatan <>", value, "jabatan");
            return (Criteria) this;
        }

        public Criteria andJabatanGreaterThan(String value) {
            addCriterion("jabatan >", value, "jabatan");
            return (Criteria) this;
        }

        public Criteria andJabatanGreaterThanOrEqualTo(String value) {
            addCriterion("jabatan >=", value, "jabatan");
            return (Criteria) this;
        }

        public Criteria andJabatanLessThan(String value) {
            addCriterion("jabatan <", value, "jabatan");
            return (Criteria) this;
        }

        public Criteria andJabatanLessThanOrEqualTo(String value) {
            addCriterion("jabatan <=", value, "jabatan");
            return (Criteria) this;
        }

        public Criteria andJabatanLike(String value) {
            addCriterion("jabatan like", value, "jabatan");
            return (Criteria) this;
        }

        public Criteria andJabatanNotLike(String value) {
            addCriterion("jabatan not like", value, "jabatan");
            return (Criteria) this;
        }

        public Criteria andJabatanIn(List<String> values) {
            addCriterion("jabatan in", values, "jabatan");
            return (Criteria) this;
        }

        public Criteria andJabatanNotIn(List<String> values) {
            addCriterion("jabatan not in", values, "jabatan");
            return (Criteria) this;
        }

        public Criteria andJabatanBetween(String value1, String value2) {
            addCriterion("jabatan between", value1, value2, "jabatan");
            return (Criteria) this;
        }

        public Criteria andJabatanNotBetween(String value1, String value2) {
            addCriterion("jabatan not between", value1, value2, "jabatan");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andTeleponIsNull() {
            addCriterion("telepon is null");
            return (Criteria) this;
        }

        public Criteria andTeleponIsNotNull() {
            addCriterion("telepon is not null");
            return (Criteria) this;
        }

        public Criteria andTeleponEqualTo(String value) {
            addCriterion("telepon =", value, "telepon");
            return (Criteria) this;
        }

        public Criteria andTeleponNotEqualTo(String value) {
            addCriterion("telepon <>", value, "telepon");
            return (Criteria) this;
        }

        public Criteria andTeleponGreaterThan(String value) {
            addCriterion("telepon >", value, "telepon");
            return (Criteria) this;
        }

        public Criteria andTeleponGreaterThanOrEqualTo(String value) {
            addCriterion("telepon >=", value, "telepon");
            return (Criteria) this;
        }

        public Criteria andTeleponLessThan(String value) {
            addCriterion("telepon <", value, "telepon");
            return (Criteria) this;
        }

        public Criteria andTeleponLessThanOrEqualTo(String value) {
            addCriterion("telepon <=", value, "telepon");
            return (Criteria) this;
        }

        public Criteria andTeleponLike(String value) {
            addCriterion("telepon like", value, "telepon");
            return (Criteria) this;
        }

        public Criteria andTeleponNotLike(String value) {
            addCriterion("telepon not like", value, "telepon");
            return (Criteria) this;
        }

        public Criteria andTeleponIn(List<String> values) {
            addCriterion("telepon in", values, "telepon");
            return (Criteria) this;
        }

        public Criteria andTeleponNotIn(List<String> values) {
            addCriterion("telepon not in", values, "telepon");
            return (Criteria) this;
        }

        public Criteria andTeleponBetween(String value1, String value2) {
            addCriterion("telepon between", value1, value2, "telepon");
            return (Criteria) this;
        }

        public Criteria andTeleponNotBetween(String value1, String value2) {
            addCriterion("telepon not between", value1, value2, "telepon");
            return (Criteria) this;
        }

        public Criteria andNamaLikeInsensitive(String value) {
            addCriterion("upper(nama) like", value.toUpperCase(), "nama");
            return (Criteria) this;
        }

        public Criteria andAlamatLikeInsensitive(String value) {
            addCriterion("upper(alamat) like", value.toUpperCase(), "alamat");
            return (Criteria) this;
        }

        public Criteria andJabatanLikeInsensitive(String value) {
            addCriterion("upper(jabatan) like", value.toUpperCase(), "jabatan");
            return (Criteria) this;
        }

        public Criteria andEmailLikeInsensitive(String value) {
            addCriterion("upper(email) like", value.toUpperCase(), "email");
            return (Criteria) this;
        }

        public Criteria andTeleponLikeInsensitive(String value) {
            addCriterion("upper(telepon) like", value.toUpperCase(), "telepon");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table penanggung_jawab
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table penanggung_jawab
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}