package com.pusilkom.base.model;

import java.io.Serializable;

public class PenanggungJawab implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penanggung_jawab.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penanggung_jawab.id_kerjasama
     *
     * @mbg.generated
     */
    private Integer idKerjasama;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penanggung_jawab.id_institusi
     *
     * @mbg.generated
     */
    private Integer idInstitusi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penanggung_jawab.nama
     *
     * @mbg.generated
     */
    private String nama;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penanggung_jawab.alamat
     *
     * @mbg.generated
     */
    private String alamat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penanggung_jawab.jabatan
     *
     * @mbg.generated
     */
    private String jabatan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penanggung_jawab.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penanggung_jawab.telepon
     *
     * @mbg.generated
     */
    private String telepon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table penanggung_jawab
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penanggung_jawab.id
     *
     * @return the value of penanggung_jawab.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penanggung_jawab.id
     *
     * @param id the value for penanggung_jawab.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penanggung_jawab.id_kerjasama
     *
     * @return the value of penanggung_jawab.id_kerjasama
     *
     * @mbg.generated
     */
    public Integer getIdKerjasama() {
        return idKerjasama;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penanggung_jawab.id_kerjasama
     *
     * @param idKerjasama the value for penanggung_jawab.id_kerjasama
     *
     * @mbg.generated
     */
    public void setIdKerjasama(Integer idKerjasama) {
        this.idKerjasama = idKerjasama;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penanggung_jawab.id_institusi
     *
     * @return the value of penanggung_jawab.id_institusi
     *
     * @mbg.generated
     */
    public Integer getIdInstitusi() {
        return idInstitusi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penanggung_jawab.id_institusi
     *
     * @param idInstitusi the value for penanggung_jawab.id_institusi
     *
     * @mbg.generated
     */
    public void setIdInstitusi(Integer idInstitusi) {
        this.idInstitusi = idInstitusi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penanggung_jawab.nama
     *
     * @return the value of penanggung_jawab.nama
     *
     * @mbg.generated
     */
    public String getNama() {
        return nama;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penanggung_jawab.nama
     *
     * @param nama the value for penanggung_jawab.nama
     *
     * @mbg.generated
     */
    public void setNama(String nama) {
        this.nama = nama;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penanggung_jawab.alamat
     *
     * @return the value of penanggung_jawab.alamat
     *
     * @mbg.generated
     */
    public String getAlamat() {
        return alamat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penanggung_jawab.alamat
     *
     * @param alamat the value for penanggung_jawab.alamat
     *
     * @mbg.generated
     */
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penanggung_jawab.jabatan
     *
     * @return the value of penanggung_jawab.jabatan
     *
     * @mbg.generated
     */
    public String getJabatan() {
        return jabatan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penanggung_jawab.jabatan
     *
     * @param jabatan the value for penanggung_jawab.jabatan
     *
     * @mbg.generated
     */
    public void setJabatan(String jabatan) {
        this.jabatan = jabatan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penanggung_jawab.email
     *
     * @return the value of penanggung_jawab.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penanggung_jawab.email
     *
     * @param email the value for penanggung_jawab.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penanggung_jawab.telepon
     *
     * @return the value of penanggung_jawab.telepon
     *
     * @mbg.generated
     */
    public String getTelepon() {
        return telepon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penanggung_jawab.telepon
     *
     * @param telepon the value for penanggung_jawab.telepon
     *
     * @mbg.generated
     */
    public void setTelepon(String telepon) {
        this.telepon = telepon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penanggung_jawab
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PenanggungJawab other = (PenanggungJawab) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIdKerjasama() == null ? other.getIdKerjasama() == null : this.getIdKerjasama().equals(other.getIdKerjasama()))
            && (this.getIdInstitusi() == null ? other.getIdInstitusi() == null : this.getIdInstitusi().equals(other.getIdInstitusi()))
            && (this.getNama() == null ? other.getNama() == null : this.getNama().equals(other.getNama()))
            && (this.getAlamat() == null ? other.getAlamat() == null : this.getAlamat().equals(other.getAlamat()))
            && (this.getJabatan() == null ? other.getJabatan() == null : this.getJabatan().equals(other.getJabatan()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getTelepon() == null ? other.getTelepon() == null : this.getTelepon().equals(other.getTelepon()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penanggung_jawab
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIdKerjasama() == null) ? 0 : getIdKerjasama().hashCode());
        result = prime * result + ((getIdInstitusi() == null) ? 0 : getIdInstitusi().hashCode());
        result = prime * result + ((getNama() == null) ? 0 : getNama().hashCode());
        result = prime * result + ((getAlamat() == null) ? 0 : getAlamat().hashCode());
        result = prime * result + ((getJabatan() == null) ? 0 : getJabatan().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getTelepon() == null) ? 0 : getTelepon().hashCode());
        return result;
    }
}