package com.pusilkom.base.model;

import java.io.Serializable;
import java.util.Date;

public class Userweb implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userweb.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userweb.kode_sso
     *
     * @mbg.generated
     */
    private String kodeSso;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userweb.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userweb.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userweb.last_login
     *
     * @mbg.generated
     */
    private Date lastLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userweb.last_ip
     *
     * @mbg.generated
     */
    private String lastIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userweb.foto
     *
     * @mbg.generated
     */
    private String foto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userweb.nip
     *
     * @mbg.generated
     */
    private String nip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userweb.nama
     *
     * @mbg.generated
     */
    private String nama;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userweb.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userweb.is_active
     *
     * @mbg.generated
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userweb.id_institusi
     *
     * @mbg.generated
     */
    private Integer idInstitusi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userweb.foto_name
     *
     * @mbg.generated
     */
    private String fotoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userweb.last_logout
     *
     * @mbg.generated
     */
    private Date lastLogout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userweb
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userweb.id
     *
     * @return the value of userweb.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userweb.id
     *
     * @param id the value for userweb.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userweb.kode_sso
     *
     * @return the value of userweb.kode_sso
     *
     * @mbg.generated
     */
    public String getKodeSso() {
        return kodeSso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userweb.kode_sso
     *
     * @param kodeSso the value for userweb.kode_sso
     *
     * @mbg.generated
     */
    public void setKodeSso(String kodeSso) {
        this.kodeSso = kodeSso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userweb.username
     *
     * @return the value of userweb.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userweb.username
     *
     * @param username the value for userweb.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userweb.password
     *
     * @return the value of userweb.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userweb.password
     *
     * @param password the value for userweb.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userweb.last_login
     *
     * @return the value of userweb.last_login
     *
     * @mbg.generated
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userweb.last_login
     *
     * @param lastLogin the value for userweb.last_login
     *
     * @mbg.generated
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userweb.last_ip
     *
     * @return the value of userweb.last_ip
     *
     * @mbg.generated
     */
    public String getLastIp() {
        return lastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userweb.last_ip
     *
     * @param lastIp the value for userweb.last_ip
     *
     * @mbg.generated
     */
    public void setLastIp(String lastIp) {
        this.lastIp = lastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userweb.foto
     *
     * @return the value of userweb.foto
     *
     * @mbg.generated
     */
    public String getFoto() {
        return foto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userweb.foto
     *
     * @param foto the value for userweb.foto
     *
     * @mbg.generated
     */
    public void setFoto(String foto) {
        this.foto = foto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userweb.nip
     *
     * @return the value of userweb.nip
     *
     * @mbg.generated
     */
    public String getNip() {
        return nip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userweb.nip
     *
     * @param nip the value for userweb.nip
     *
     * @mbg.generated
     */
    public void setNip(String nip) {
        this.nip = nip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userweb.nama
     *
     * @return the value of userweb.nama
     *
     * @mbg.generated
     */
    public String getNama() {
        return nama;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userweb.nama
     *
     * @param nama the value for userweb.nama
     *
     * @mbg.generated
     */
    public void setNama(String nama) {
        this.nama = nama;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userweb.email
     *
     * @return the value of userweb.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userweb.email
     *
     * @param email the value for userweb.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userweb.is_active
     *
     * @return the value of userweb.is_active
     *
     * @mbg.generated
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userweb.is_active
     *
     * @param isActive the value for userweb.is_active
     *
     * @mbg.generated
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userweb.id_institusi
     *
     * @return the value of userweb.id_institusi
     *
     * @mbg.generated
     */
    public Integer getIdInstitusi() {
        return idInstitusi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userweb.id_institusi
     *
     * @param idInstitusi the value for userweb.id_institusi
     *
     * @mbg.generated
     */
    public void setIdInstitusi(Integer idInstitusi) {
        this.idInstitusi = idInstitusi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userweb.foto_name
     *
     * @return the value of userweb.foto_name
     *
     * @mbg.generated
     */
    public String getFotoName() {
        return fotoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userweb.foto_name
     *
     * @param fotoName the value for userweb.foto_name
     *
     * @mbg.generated
     */
    public void setFotoName(String fotoName) {
        this.fotoName = fotoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userweb.last_logout
     *
     * @return the value of userweb.last_logout
     *
     * @mbg.generated
     */
    public Date getLastLogout() {
        return lastLogout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userweb.last_logout
     *
     * @param lastLogout the value for userweb.last_logout
     *
     * @mbg.generated
     */
    public void setLastLogout(Date lastLogout) {
        this.lastLogout = lastLogout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userweb
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Userweb other = (Userweb) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getKodeSso() == null ? other.getKodeSso() == null : this.getKodeSso().equals(other.getKodeSso()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getLastLogin() == null ? other.getLastLogin() == null : this.getLastLogin().equals(other.getLastLogin()))
            && (this.getLastIp() == null ? other.getLastIp() == null : this.getLastIp().equals(other.getLastIp()))
            && (this.getFoto() == null ? other.getFoto() == null : this.getFoto().equals(other.getFoto()))
            && (this.getNip() == null ? other.getNip() == null : this.getNip().equals(other.getNip()))
            && (this.getNama() == null ? other.getNama() == null : this.getNama().equals(other.getNama()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getIsActive() == null ? other.getIsActive() == null : this.getIsActive().equals(other.getIsActive()))
            && (this.getIdInstitusi() == null ? other.getIdInstitusi() == null : this.getIdInstitusi().equals(other.getIdInstitusi()))
            && (this.getFotoName() == null ? other.getFotoName() == null : this.getFotoName().equals(other.getFotoName()))
            && (this.getLastLogout() == null ? other.getLastLogout() == null : this.getLastLogout().equals(other.getLastLogout()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userweb
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getKodeSso() == null) ? 0 : getKodeSso().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getLastLogin() == null) ? 0 : getLastLogin().hashCode());
        result = prime * result + ((getLastIp() == null) ? 0 : getLastIp().hashCode());
        result = prime * result + ((getFoto() == null) ? 0 : getFoto().hashCode());
        result = prime * result + ((getNip() == null) ? 0 : getNip().hashCode());
        result = prime * result + ((getNama() == null) ? 0 : getNama().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getIsActive() == null) ? 0 : getIsActive().hashCode());
        result = prime * result + ((getIdInstitusi() == null) ? 0 : getIdInstitusi().hashCode());
        result = prime * result + ((getFotoName() == null) ? 0 : getFotoName().hashCode());
        result = prime * result + ((getLastLogout() == null) ? 0 : getLastLogout().hashCode());
        return result;
    }
}