# CI/CD jobs to automate deployment
.deploy-base:
  image: alpine:3.12.0
  stage: deploy
  cache: {}
  variables:
    ENVIRONMENT_IP: 127.0.0.1
    ENVIRONMENT_NAME: develop
    DEPLOYER_PRIVATE_KEY:
    DEPLOYER_USER:
  before_script:
    - apk update
    - 'which ssh-agent || ( apk update && apk add openssh-client rsync )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - echo "${DEPLOYER_PRIVATE_KEY}" | ssh-add -
    - ssh-keyscan -H "${ENVIRONMENT_IP}" >> ~/.ssh/known_hosts
    - export TIMESTAMP="$(date +%Y%m%d%H%M%S)"
    - ls dist/
  script:
    - rsync -rav dist/
      "${DEPLOYER_USER}@${ENVIRONMENT_IP}:/opt/unhan/sikerjasama/frontend/${ENVIRONMENT_NAME}/releases/${TIMESTAMP}"
    - ssh "${DEPLOYER_USER}@${ENVIRONMENT_IP}"
      "rm /opt/unhan/sikerjasama/frontend/${ENVIRONMENT_NAME}/current | true"
    - ssh "${DEPLOYER_USER}@${ENVIRONMENT_IP}"
      "ln -s /opt/unhan/sikerjasama/frontend/${ENVIRONMENT_NAME}/releases/${TIMESTAMP} /opt/unhan/sikerjasama/frontend/${ENVIRONMENT_NAME}/current"
  except:
    refs:
      - schedules
